export const FETCH_USER_CONFIG = "FETCH_USER_CONFIG";
export const FETCH_USER_CONFIG_SUCCESS = "FETCH_USER_CONFIG_SUCCESS";
export const FETCH_USER_CONFIG_FAIL = "FETCH_USER_CONFIG_FAIL";
export const USER_CONFIG_UPDATE = "USER_CONFIG_UPDATE";