export const FETCH_NOTIFICATION_DATA = "FETCH_NOTIFICATION_DATA";
export const FETCH_NOTIFICATION_SUCCESS = "FETCH_NOTIFICATION_SUCCESS";
export const FETCH_NOTIFICATION_FAIL = "FETCH_NOTIFICATION_FAIL";
export const NOTIFICATION_UPDATE = "NOTIFICATION_UPDATE";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
