export const FETCH_USER_DATA = "FETCH_USER_DATA";
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAIL = "FETCH_USER_DATA_FAIL";
export const FETCH_USER_DATA_UPDATE = "FETCH_USER_DATA_UPDATE";
export const USER_DATA_UPDATE_CONSTRAINTS = "USER_DATA_UPDATE_CONSTRAINTS";
export const USER_DATA_UPDATE_AUTOACTIONS = "USER_DATA_UPDATE_AUTOACTIONS";
